/** Canonical IPC channel names shared by preload and main. */
export const IPC = {
  appInfo: 'app:info',
  appUpdateStatus: 'app:updateStatus',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  settingsReset: 'settings:reset',
  dialogPickFolder: 'dialog:pickFolder',
  shellReveal: 'shell:reveal',
  shellOpen: 'shell:open',
  clipboardRead: 'clipboard:read',
  probe: 'video:probe',
  jobsList: 'jobs:list',
  jobsCreate: 'jobs:create',
  jobsCancel: 'jobs:cancel',
  jobsRemove: 'jobs:remove',
  jobsRetry: 'jobs:retry',
  jobsClearFinished: 'jobs:clearFinished',
  jobsProgress: 'jobs:progress',
  libraryScan: 'library:scan',
  libraryDelete: 'library:delete',
  streamResolve: 'stream:resolve',
  streamRelease: 'stream:release',
  toolsStatus: 'tools:status',
  toolsCheckUpdate: 'tools:checkUpdate',
  toolsUpdateYtdlp: 'tools:updateYtdlp',
  toolsInstallFfmpeg: 'tools:installFfmpeg',
  toolsOpenBin: 'tools:openBin',
  toolsOpenFfmpegDownload: 'tools:openFfmpegDownload',
  dialogPickFile: 'dialog:pickFile',
  notifyToast: 'app:toast',
} as const
